name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files (debug)
        run: ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9

      - name: Build debug APK
        run: gradle assembleDebug
        working-directory: CutCoachRepo   # <-- put the folder that contains settings.gradle

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CutCoach-debug-apk
          path: CutCoachRepo/app/build/outputs/apk/debug/app-debug.apk
