name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug: list repo and locate settings.gradle
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "Searching for settings.gradle..."
          find . -type f -name settings.gradle -print

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      # Use supported Gradle for AGP 8.5.x
      - name: Set up Gradle (8.7)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build debug APK (auto-detect project dir)
        run: |
          PROJ_DIR="$(dirname "$(find . -type f -name settings.gradle | head -n1)")"
          echo "Project directory: $PROJ_DIR"
          cd "$PROJ_DIR"
          gradle --version
          gradle assembleDebug --stacktrace

      - name: Upload APK artifact (glob)
        uses: actions/upload-artifact@v4
        with:
          name: CutCoach-debug-apk
          path: "**/app/build/outputs/apk/debug/app-debug.apk"
